CREATE TABLE IF NOT EXISTS users (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(255),
email VARCHAR(512),
CONSTRAINT email_uniqueness UNIQUE(email)
);

CREATE TABLE IF NOT EXISTS requests (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
description VARCHAR(1024),
requester_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
created TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS items (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(255),
description VARCHAR(2048),
available BOOLEAN,
owner_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
request_id BIGINT REFERENCES requests (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
start TIMESTAMP WITHOUT TIME ZONE,
end_b TIMESTAMP WITHOUT TIME ZONE,
item_id BIGINT REFERENCES items (id) ON DELETE CASCADE,
booker_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
status INT
);

CREATE TABLE IF NOT EXISTS comments (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
text VARCHAR(1024),
item_id BIGINT REFERENCES items (id) ON DELETE CASCADE,
author_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
created TIMESTAMP WITHOUT TIME ZONE
);